# Generated by Django 2.2 on 2022-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('predictions', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['comment'],
            },
        ),
    ]
