# Generated by Django 2.2 on 2022-05-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_auto_20220518_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='comment_length',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='predictions',
            field=models.BinaryField(blank=True),
        ),
    ]
