# Generated by Django 2.2 on 2022-05-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0003_auto_20220518_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='comment_length',
            field=models.IntegerField(null=True),
        ),
    ]
