# Generated by Django 2.2 on 2022-05-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0005_auto_20220518_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='predictions',
            field=models.IntegerField(blank=True),
        ),
    ]
